import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/globe.svg" />
      </Head>
      <div className="flex flex-col items-center justify-center min-h-screen bg-gray-100">
        <Link href="/dashboard">
          <h1 className="text-3xl font-bold underline">Go to Dashboard</h1>
        </Link>
      </div>
    </>
  );
}
